stigforge_role: rhel9_cis
stigforge_profile: cis-l1
stigforge_rules_enabled: true
stigforge_min_score: 90
stigforge_ssg_datastream: ssg-rhel9-ds.xml
stigforge_ssg_profile: xccdf_org.ssgproject.content_profile_cis_server_l1
